language: node_js
node_js:
- '7'
cache: yarn
before_script:
- yarn lint
- yarn build
env:
  global:
    secure: BPfTCGB6jZdLTA6Hf1bCEb1vIbmB1fEvnejUFhzBH6uHRgHzDHUsFrxGGqTle/3syypFxlXCaAd7LOTbFdCfaEc/FoxEWGtAEGfV5RgQBkDRzdOs44bHa89pK/zARjcrgDGVPU8/GddZ+D0DBryWGMmRcluzOttOCsbxDVvPsZzD+B8TtQEszCtVb7j/qyxxZ159/nYKJoo4bRZ2SSoE+VskU117asOelMk2w4wyx6IfsTU1iqFSKrVN0B6bYBTWHjNm3ENXw5Xie+syMTq58RFvRLj/ML4+f8ZHfwQ+v8XhZuoQvlV6gAOAecuwYo3j4wOeepcl67v7e8kdI2b9YwUyIyCNHNBieTiAYlaukqRc2Hz7YEscwuGr6oE9YxZIsrSWkPDCJ18uokDWW4V/xj2SjcKSKxYT693TJgcxLZX6yD59oKfq/owWdhL76Q4hP0rbJq89MfvFuaOVYydnKBMEg2IesDAvhJCqnrCwURAM6fw13JSrgOeiwZg3m0KJ8X4Oq1CtvS8JZPHfI6Zuvkj/1pjdNIzX0+Ya0ZA/ekGFuKfQnOHM5b4P1OYao1qUqK2OiOh9vMa8wwUOKOX8haa7a55tHzj7Mvl6dwWG2CZURFuupJ9bxKKVzPZZbk+LftH0kfWn/obLKyzApnX3F6BQHQTQ4UG5yYQf4iqP4HY=
